# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-09-27
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT & CC BY-NC-SA (https://www.altikva.com/licenses/LICENSE-1.0)"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: Seed one checkout's .codegraph store from another's, so a fresh
#              worktree of the same repo starts warm instead of paying a full
#              index. Copies the graph DB, the FTS DB and the knowledge/plan
#              store, then rewrites every stored absolute path (and the symbol
#              and edge ids that embed it) from the source root to the target
#              root. Because graph node paths and ids all begin with the same
#              absolute-root prefix, one prefix rewrite fixes them together,
#              independent of which column holds them. The caller then runs an
#              incremental reindex, which touches only the files that differ.

from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
from pathlib import Path

from codegraph.core.db import _DUCKDB_FILE, _SQLITE_FILE, _backend, reset_connection
from codegraph.state.scan_meta import _meta_path, read_meta

# Files carried from the source store. The graph file is chosen by backend.
# Everything else (auth.key, activity.log, owner.*, workers/, findings.db,
# bugreports/) is per-checkout runtime or derived state and is never copied:
# the target mints its own auth key, findings are regenerated by the scanners,
# and the owner/worker markers must describe the target's own processes.
_FTS_FILE = "fts.db"
_CALL_LOG_FILE = "call_log.db"
_CONFIG_FILE = "config.toml"


class RelocateError(Exception):
    """The source store cannot be seeded from (missing, or held by an owner)."""


def _sidecars(path: Path, suffixes: tuple[str, ...]) -> list[Path]:
    return [path.with_name(path.name + s) for s in suffixes]


def _copy_sqlite(src: Path, dst: Path) -> None:
    """Copy a SQLite database through the backup API, not byte for byte.

    The stores run in WAL mode, so committed pages can still sit in the
    source's ``-wal`` file: a plain copy of the main file alone yields a torn
    database ("database disk image is malformed" on first use). The backup API
    reads a consistent snapshot that includes the WAL. Any ``-wal``/``-shm``
    left in the target by an earlier store is removed first, since SQLite would
    otherwise replay those foreign pages over the fresh copy."""
    for p in (dst, *_sidecars(dst, ("-wal", "-shm", "-journal"))):
        p.unlink(missing_ok=True)
    s = sqlite3.connect(str(src))
    try:
        d = sqlite3.connect(str(dst))
        try:
            s.backup(d)
        finally:
            d.close()
    finally:
        s.close()


def _rewrite_prefix_generic(con, columns, old_prefix: str, new_prefix: str) -> int:
    """Rewrite the leading ``old_prefix`` to ``new_prefix`` in every listed
    (table, column). Match by a substring-equality anchor rather than LIKE so a
    path containing a LIKE metacharacter (``%``, ``_``) cannot slip the filter,
    and rewrite only the leading run via ``substr`` so a value that happens to
    repeat the old root deeper inside is left intact. Identifiers come from the
    schema itself, never a caller, but are still quoted."""
    plen = len(old_prefix)
    changed = 0
    for tbl, col in columns:
        qtbl = '"' + tbl.replace('"', '""') + '"'
        qcol = '"' + col.replace('"', '""') + '"'
        where = f"substr({qcol}, 1, ?) = ?"
        n = con.execute(
            f"SELECT count(*) FROM {qtbl} WHERE {where}", [plen, old_prefix]
        ).fetchone()[0]
        if not n:
            continue
        con.execute(
            f"UPDATE {qtbl} SET {qcol} = ? || substr({qcol}, ?) WHERE {where}",
            [new_prefix, plen + 1, plen, old_prefix],
        )
        changed += int(n)
    return changed


def _quote(ident: str) -> str:
    return '"' + ident.replace('"', '""') + '"'


def _relocate_duckdb(
    src: Path, dst: Path, old_prefix: str, new_prefix: str
) -> tuple[int, list[str]]:
    """Build the target graph fresh and copy the source rows into it with the
    paths already rewritten.

    Rewriting in place with UPDATE touches key columns (every node id and edge
    key embeds the path), and DuckDB runs an UPDATE of an indexed column as an
    index delete plus insert. On some real stores that delete loses keys and
    the whole database is invalidated ("Failed to delete all rows from index.
    Only deleted 181 out of 191 rows"), although the source is consistent. So
    no key is ever updated here: the target schema comes from init_schema and
    each row is inserted once with its final values, which also builds every
    index from correct keys. Columns and tables the current schema does not
    know (a store written by a newer cgh) are not copied, and are returned so
    the caller can say so. Row counts are checked per table.

    Returns (values rewritten, tables or columns left out)."""
    import duckdb

    from codegraph.core.schema_duckdb import init_schema

    for p in (dst, *_sidecars(dst, (".wal",))):
        p.unlink(missing_ok=True)

    plen = len(old_prefix)
    rewritten = 0
    left_out: list[str] = []
    con = duckdb.connect(str(dst))
    try:
        init_schema(con)
        target_db = con.execute("SELECT current_database()").fetchone()[0]
        con.execute(
            f"ATTACH '{str(src).replace(chr(39), chr(39) * 2)}' AS src_db (READ_ONLY)"
        )

        def columns(catalog: str, table: str) -> dict[str, str]:
            return dict(
                con.execute(
                    "SELECT column_name, data_type FROM information_schema.columns "
                    "WHERE table_catalog = ? AND table_schema = 'main' "
                    "AND table_name = ? ORDER BY ordinal_position",
                    [catalog, table],
                ).fetchall()
            )

        tables = [
            r[0]
            for r in con.execute(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_catalog = 'src_db' AND table_schema = 'main' "
                "AND table_type = 'BASE TABLE'"
            ).fetchall()
        ]
        for table in tables:
            src_cols, dst_cols = columns("src_db", table), columns(target_db, table)
            if not dst_cols:
                left_out.append(table)
                continue
            left_out.extend(f"{table}.{c}" for c in src_cols if c not in dst_cols)
            shared = [c for c in dst_cols if c in src_cols]
            exprs = []
            for c in shared:
                qc = _quote(c)
                if src_cols[c] in ("VARCHAR", "TEXT"):
                    rewritten += con.execute(
                        f"SELECT count(*) FROM src_db.main.{_quote(table)} "
                        f"WHERE substr({qc}, 1, {plen}) = $old",
                        {"old": old_prefix},
                    ).fetchone()[0]
                    exprs.append(
                        f"CASE WHEN substr({qc}, 1, {plen}) = $old "
                        f"THEN $new || substr({qc}, {plen + 1}) ELSE {qc} END"
                    )
                else:
                    exprs.append(qc)
            con.execute(
                f"INSERT INTO main.{_quote(table)} ({', '.join(map(_quote, shared))}) "
                f"SELECT {', '.join(exprs)} FROM src_db.main.{_quote(table)}",
                {"old": old_prefix, "new": new_prefix},
            )
            n_src = con.execute(
                f"SELECT count(*) FROM src_db.main.{_quote(table)}"
            ).fetchone()[0]
            n_dst = con.execute(
                f"SELECT count(*) FROM main.{_quote(table)}"
            ).fetchone()[0]
            if n_src != n_dst:
                raise RelocateError(
                    f"{table}: copied {n_dst} of {n_src} rows into the new graph"
                )
        con.execute("DETACH src_db")
        con.commit()
    finally:
        con.close()
    return rewritten, left_out


def _sqlite_text_columns(con, table: str) -> list[tuple[str, str]]:
    cols = []
    qtable = '"' + table.replace('"', '""') + '"'
    for row in con.execute(f"PRAGMA table_info({qtable})").fetchall():
        decl = (row[2] or "").upper()
        # SQLite is dynamically typed: an untyped column can still hold text.
        if decl == "" or "CHAR" in decl or "TEXT" in decl or "CLOB" in decl:
            cols.append((table, row[1]))
    return cols


def _rewrite_sqlite_tables(
    path: Path, tables: list[str], old_prefix: str, new_prefix: str
) -> int:
    con = sqlite3.connect(str(path))
    try:
        columns: list[tuple[str, str]] = []
        for t in tables:
            columns.extend(_sqlite_text_columns(con, t))
        changed = _rewrite_prefix_generic(con, columns, old_prefix, new_prefix)
        con.commit()
        return changed
    finally:
        con.close()


def _rewrite_sqlite_graph(path: Path, old_prefix: str, new_prefix: str) -> int:
    con = sqlite3.connect(str(path))
    try:
        tables = [
            r[0]
            for r in con.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' "
                "AND name NOT LIKE 'sqlite_%'"
            ).fetchall()
        ]
    finally:
        con.close()
    return _rewrite_sqlite_tables(path, tables, old_prefix, new_prefix)


def _rewrite_fts(path: Path, old_prefix: str, new_prefix: str) -> int:
    # The graph FTS keeps a plain ``symbols`` table (sym_id + file_path both hold
    # the absolute path) alongside the fts5 shadow indexes. The shadows index
    # only name and docstring, which the rewrite does not touch, so editing the
    # base table's paths leaves them consistent with no resync. Only the paths in
    # the base table need moving; the memory and plan tables are path-free.
    con = sqlite3.connect(str(path))
    try:
        has_symbols = con.execute(
            "SELECT count(*) FROM sqlite_master WHERE type = 'table' AND name = 'symbols'"
        ).fetchone()[0]
    finally:
        con.close()
    if not has_symbols:
        return 0
    return _rewrite_sqlite_tables(path, ["symbols"], old_prefix, new_prefix)


def _rewrite_call_log_refs(path: Path, old_prefix: str, new_prefix: str) -> int:
    # Knowledge entries carry file_refs as a JSON array of absolute paths. These
    # are informational, so this is best-effort: a plain substring replace over
    # the JSON text is enough, and any occurrence of the source root belongs to a
    # path from that checkout. Left untouched if the column or table is absent.
    con = sqlite3.connect(str(path))
    try:
        n = con.execute(
            "SELECT count(*) FROM knowledge WHERE file_refs LIKE '%' || ? || '%'",
            [old_prefix],
        ).fetchone()[0]
        if n:
            con.execute(
                "UPDATE knowledge SET file_refs = replace(file_refs, ?, ?) "
                "WHERE file_refs LIKE '%' || ? || '%'",
                [old_prefix, new_prefix, old_prefix],
            )
            con.commit()
        return int(n)
    except sqlite3.OperationalError:
        return 0
    finally:
        con.close()


def _rewrite_scan_meta(from_root: Path, to_root: Path) -> None:
    # Carry the source metadata but stamp the target root. incremental_reindex
    # forces a full rebuild when the recorded root differs from the live one, so
    # the root must read as the target for the copied paths to be trusted; the
    # git head and blob shas stay as the source's, and the next incremental pass
    # advances them to the target's working tree.
    meta = read_meta(from_root) or {}
    meta["root"] = str(to_root.resolve())
    dst = _meta_path(to_root)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")


_TABLE_HEADER = re.compile(r"^\s*\[\[?\s*([^\]]+?)\s*\]\]?\s*(#.*)?$")
_SUBREPOS_KEY = re.compile(r"^\s*subrepos\s*=")


def _drop_subrepos(config_path: Path) -> list[str]:
    """Remove ``subrepos`` from the ``[codegraph]`` table of a seeded config.

    Federation links one checkout to other checkouts, which the seed does not
    carry. The source's children are its own: absolute paths to other repos'
    main checkouts, each on whatever branch it holds. A per-ticket worktree
    that inherited them would fan its queries out to code on unrelated
    branches. It starts unfederated instead; ``cgh federate add`` re-links it.

    The assignment is cut line by line rather than by re-emitting the parsed
    file: a re-emit drops comments and flattens nested tables such as
    ``[plugin.codegen]``. A multi-line array is followed to its closing
    bracket. Returns the removed entries, empty when there were none. If the
    edited text does not parse, the file is left untouched and nothing is
    reported as removed."""
    import tomllib

    try:
        text = config_path.read_text(encoding="utf-8")
        entries = list(tomllib.loads(text).get("codegraph", {}).get("subrepos", []))
    except (OSError, tomllib.TOMLDecodeError):
        return []
    if not entries:
        return []

    kept: list[str] = []
    table = ""
    depth = 0  # open brackets of a subrepos array still being skipped
    for line in text.splitlines(keepends=True):
        if depth:
            depth += line.count("[") - line.count("]")
            continue
        header = _TABLE_HEADER.match(line)
        if header:
            table = header.group(1)
        elif table == "codegraph" and _SUBREPOS_KEY.match(line):
            value = line.split("=", 1)[1]
            depth = value.count("[") - value.count("]")
            continue
        kept.append(line)

    edited = "".join(kept)
    try:
        if "subrepos" in tomllib.loads(edited).get("codegraph", {}):
            return []
    except tomllib.TOMLDecodeError:
        return []
    config_path.write_text(edited, encoding="utf-8")
    return [str(e) for e in entries]


def _split_table(text: str, name: str) -> tuple[str, str]:
    """Cut the ``[name]`` table out of a TOML text, line by line: returns the
    text without it and the table's own lines (header included), empty when
    absent. Line-level for the same reason as _drop_subrepos."""
    kept: list[str] = []
    block: list[str] = []
    inside = False
    for line in text.splitlines(keepends=True):
        header = _TABLE_HEADER.match(line)
        if header:
            inside = header.group(1) == name
        (block if inside else kept).append(line)
    return "".join(kept), "".join(block)


def _keep_target_plugins(config_path: Path, target_text: str | None) -> bool:
    """Put the target's own ``[plugins]`` table back into a seeded config.

    The seed copies the source's config over the target's, so a plugin the
    target had disabled (summarize, in a per-ticket worktree) came back on and
    the follow-up index called it for every changed file. Returns True when
    the target's table was restored; on a text that would not parse, the
    copied config is left as is."""
    import tomllib

    if not target_text:
        return False
    _, block = _split_table(target_text, "plugins")
    if not block.strip():
        return False
    try:
        copied = config_path.read_text(encoding="utf-8")
    except OSError:
        return False
    without, _ = _split_table(copied, "plugins")
    edited = without.rstrip("\n") + "\n\n" + block.rstrip("\n") + "\n"
    try:
        tomllib.loads(edited)
    except tomllib.TOMLDecodeError:
        return False
    config_path.write_text(edited, encoding="utf-8")
    return True


def relocate_store(from_root: str | Path, to_root: str | Path) -> dict:
    """Seed ``to_root``'s .codegraph from ``from_root``'s.

    Copies the graph DB, the FTS DB, the knowledge/plan store and the config,
    then rewrites every stored path and embedded id from the source root to the
    target root. The target's ``.codegraph`` directory must already exist (run
    ``init_project`` first). Returns a summary dict; the caller is expected to
    run an incremental reindex afterward so branch-changed files are refreshed.

    Raises ``RelocateError`` if the source has no graph to copy.
    """
    from_root = Path(from_root).resolve()
    to_root = Path(to_root).resolve()
    from_cg = from_root / ".codegraph"
    to_cg = to_root / ".codegraph"
    to_cg.mkdir(parents=True, exist_ok=True)

    backend = _backend(from_root)
    graph_file = _DUCKDB_FILE if backend == "duckdb" else _SQLITE_FILE
    if not (from_cg / graph_file).exists():
        raise RelocateError(f"no {graph_file} under {from_cg} to seed from")

    # The calling process may already hold the target's graph open (init probes
    # the existing store first). DuckDB refuses a second open of the same file
    # with a different configuration, and the copy replaces the file under it,
    # so every cached connection to the target is released before anything moves.
    reset_connection(to_root)

    old_prefix = str(from_root) + os.sep
    new_prefix = str(to_root) + os.sep
    rewritten = 0
    left_out: list[str] = []

    try:
        target_config: str | None = (to_cg / _CONFIG_FILE).read_text(encoding="utf-8")
    except OSError:
        target_config = None

    copied: list[str] = []
    for name in (graph_file, _FTS_FILE, _CALL_LOG_FILE, _CONFIG_FILE):
        src = from_cg / name
        if not src.exists():
            continue
        dst = to_cg / name
        if name == _DUCKDB_FILE:
            # Built, not copied: see _relocate_duckdb for why no key is updated.
            rewritten, left_out = _relocate_duckdb(src, dst, old_prefix, new_prefix)
        elif name == _CONFIG_FILE:
            shutil.copy2(src, dst)
        else:
            _copy_sqlite(src, dst)
        copied.append(name)

    if backend != "duckdb":
        rewritten += _rewrite_sqlite_graph(to_cg / graph_file, old_prefix, new_prefix)
    if _FTS_FILE in copied:
        rewritten += _rewrite_fts(to_cg / _FTS_FILE, old_prefix, new_prefix)
    if _CALL_LOG_FILE in copied:
        rewritten += _rewrite_call_log_refs(
            to_cg / _CALL_LOG_FILE, old_prefix, new_prefix
        )

    _rewrite_scan_meta(from_root, to_root)
    dropped = _drop_subrepos(to_cg / _CONFIG_FILE) if _CONFIG_FILE in copied else []
    if _CONFIG_FILE in copied:
        _keep_target_plugins(to_cg / _CONFIG_FILE, target_config)

    return {
        "backend": backend,
        "copied": copied,
        "rewritten_rows": rewritten,
        "dropped_subrepos": dropped,
        "left_out": left_out,
        "from_root": str(from_root),
        "to_root": str(to_root),
    }
