# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-09-27
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT & CC BY-NC-SA (https://www.altikva.com/licenses/LICENSE-1.0)"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: Seed one checkout's .codegraph store from another's, so a fresh
#              worktree of the same repo starts warm instead of paying a full
#              index. Copies the graph DB, the FTS DB and the knowledge/plan
#              store, then rewrites every stored absolute path (and the symbol
#              and edge ids that embed it) from the source root to the target
#              root. Because graph node paths and ids all begin with the same
#              absolute-root prefix, one prefix rewrite fixes them together,
#              independent of which column holds them. The caller then runs an
#              incremental reindex, which touches only the files that differ.

from __future__ import annotations

import json
import os
import re
import shutil
import sqlite3
from pathlib import Path

from codegraph.core.db import _DUCKDB_FILE, _SQLITE_FILE, _backend, reset_connection
from codegraph.state.scan_meta import _meta_path, read_meta

# Files carried from the source store. The graph file is chosen by backend.
# Everything else (auth.key, activity.log, owner.*, workers/, findings.db,
# bugreports/) is per-checkout runtime or derived state and is never copied:
# the target mints its own auth key, findings are regenerated by the scanners,
# and the owner/worker markers must describe the target's own processes.
_FTS_FILE = "fts.db"
_CALL_LOG_FILE = "call_log.db"
_CONFIG_FILE = "config.toml"


class RelocateError(Exception):
    """The source store cannot be seeded from (missing, or held by an owner)."""


def _sidecars(path: Path, suffixes: tuple[str, ...]) -> list[Path]:
    return [path.with_name(path.name + s) for s in suffixes]


def _copy_sqlite(src: Path, dst: Path) -> None:
    """Copy a SQLite database through the backup API, not byte for byte.

    The stores run in WAL mode, so committed pages can still sit in the
    source's ``-wal`` file: a plain copy of the main file alone yields a torn
    database ("database disk image is malformed" on first use). The backup API
    reads a consistent snapshot that includes the WAL. Any ``-wal``/``-shm``
    left in the target by an earlier store is removed first, since SQLite would
    otherwise replay those foreign pages over the fresh copy."""
    for p in (dst, *_sidecars(dst, ("-wal", "-shm", "-journal"))):
        p.unlink(missing_ok=True)
    s = sqlite3.connect(str(src))
    try:
        d = sqlite3.connect(str(dst))
        try:
            s.backup(d)
        finally:
            d.close()
    finally:
        s.close()


def _copy_duckdb(src: Path, dst: Path) -> None:
    """Copy a DuckDB file with its WAL, dropping any stale target WAL.

    DuckDB replays ``<file>.wal`` on open, so the source's WAL must travel with
    it (the source owner is down, so the pair is consistent) and a WAL left by
    the target's previous store must not survive to be replayed onto the copy."""
    (dst_wal,) = _sidecars(dst, (".wal",))
    dst.unlink(missing_ok=True)
    dst_wal.unlink(missing_ok=True)
    shutil.copy2(src, dst)
    (src_wal,) = _sidecars(src, (".wal",))
    if src_wal.exists():
        shutil.copy2(src_wal, dst_wal)


def _text_columns_duckdb(con) -> list[tuple[str, str]]:
    rows = con.execute(
        "SELECT table_name, column_name FROM information_schema.columns "
        "WHERE table_schema = 'main' AND data_type IN ('VARCHAR', 'TEXT')"
    ).fetchall()
    return [(t, c) for t, c in rows]


def _rewrite_prefix_generic(con, columns, old_prefix: str, new_prefix: str) -> int:
    """Rewrite the leading ``old_prefix`` to ``new_prefix`` in every listed
    (table, column). Match by a substring-equality anchor rather than LIKE so a
    path containing a LIKE metacharacter (``%``, ``_``) cannot slip the filter,
    and rewrite only the leading run via ``substr`` so a value that happens to
    repeat the old root deeper inside is left intact. Identifiers come from the
    schema itself, never a caller, but are still quoted."""
    plen = len(old_prefix)
    changed = 0
    for tbl, col in columns:
        qtbl = '"' + tbl.replace('"', '""') + '"'
        qcol = '"' + col.replace('"', '""') + '"'
        where = f"substr({qcol}, 1, ?) = ?"
        n = con.execute(
            f"SELECT count(*) FROM {qtbl} WHERE {where}", [plen, old_prefix]
        ).fetchone()[0]
        if not n:
            continue
        con.execute(
            f"UPDATE {qtbl} SET {qcol} = ? || substr({qcol}, ?) WHERE {where}",
            [new_prefix, plen + 1, plen, old_prefix],
        )
        changed += int(n)
    return changed


def _rewrite_duckdb(path: Path, old_prefix: str, new_prefix: str) -> int:
    import duckdb

    con = duckdb.connect(str(path))
    try:
        changed = _rewrite_prefix_generic(
            con, _text_columns_duckdb(con), old_prefix, new_prefix
        )
        con.commit()
        return changed
    finally:
        con.close()


def _sqlite_text_columns(con, table: str) -> list[tuple[str, str]]:
    cols = []
    qtable = '"' + table.replace('"', '""') + '"'
    for row in con.execute(f"PRAGMA table_info({qtable})").fetchall():
        decl = (row[2] or "").upper()
        # SQLite is dynamically typed: an untyped column can still hold text.
        if decl == "" or "CHAR" in decl or "TEXT" in decl or "CLOB" in decl:
            cols.append((table, row[1]))
    return cols


def _rewrite_sqlite_tables(
    path: Path, tables: list[str], old_prefix: str, new_prefix: str
) -> int:
    con = sqlite3.connect(str(path))
    try:
        columns: list[tuple[str, str]] = []
        for t in tables:
            columns.extend(_sqlite_text_columns(con, t))
        changed = _rewrite_prefix_generic(con, columns, old_prefix, new_prefix)
        con.commit()
        return changed
    finally:
        con.close()


def _rewrite_sqlite_graph(path: Path, old_prefix: str, new_prefix: str) -> int:
    con = sqlite3.connect(str(path))
    try:
        tables = [
            r[0]
            for r in con.execute(
                "SELECT name FROM sqlite_master WHERE type = 'table' "
                "AND name NOT LIKE 'sqlite_%'"
            ).fetchall()
        ]
    finally:
        con.close()
    return _rewrite_sqlite_tables(path, tables, old_prefix, new_prefix)


def _rewrite_fts(path: Path, old_prefix: str, new_prefix: str) -> int:
    # The graph FTS keeps a plain ``symbols`` table (sym_id + file_path both hold
    # the absolute path) alongside the fts5 shadow indexes. The shadows index
    # only name and docstring, which the rewrite does not touch, so editing the
    # base table's paths leaves them consistent with no resync. Only the paths in
    # the base table need moving; the memory and plan tables are path-free.
    con = sqlite3.connect(str(path))
    try:
        has_symbols = con.execute(
            "SELECT count(*) FROM sqlite_master WHERE type = 'table' AND name = 'symbols'"
        ).fetchone()[0]
    finally:
        con.close()
    if not has_symbols:
        return 0
    return _rewrite_sqlite_tables(path, ["symbols"], old_prefix, new_prefix)


def _rewrite_call_log_refs(path: Path, old_prefix: str, new_prefix: str) -> int:
    # Knowledge entries carry file_refs as a JSON array of absolute paths. These
    # are informational, so this is best-effort: a plain substring replace over
    # the JSON text is enough, and any occurrence of the source root belongs to a
    # path from that checkout. Left untouched if the column or table is absent.
    con = sqlite3.connect(str(path))
    try:
        n = con.execute(
            "SELECT count(*) FROM knowledge WHERE file_refs LIKE '%' || ? || '%'",
            [old_prefix],
        ).fetchone()[0]
        if n:
            con.execute(
                "UPDATE knowledge SET file_refs = replace(file_refs, ?, ?) "
                "WHERE file_refs LIKE '%' || ? || '%'",
                [old_prefix, new_prefix, old_prefix],
            )
            con.commit()
        return int(n)
    except sqlite3.OperationalError:
        return 0
    finally:
        con.close()


def _rewrite_scan_meta(from_root: Path, to_root: Path) -> None:
    # Carry the source metadata but stamp the target root. incremental_reindex
    # forces a full rebuild when the recorded root differs from the live one, so
    # the root must read as the target for the copied paths to be trusted; the
    # git head and blob shas stay as the source's, and the next incremental pass
    # advances them to the target's working tree.
    meta = read_meta(from_root) or {}
    meta["root"] = str(to_root.resolve())
    dst = _meta_path(to_root)
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")


_TABLE_HEADER = re.compile(r"^\s*\[\[?\s*([^\]]+?)\s*\]\]?\s*(#.*)?$")
_SUBREPOS_KEY = re.compile(r"^\s*subrepos\s*=")


def _drop_subrepos(config_path: Path) -> list[str]:
    """Remove ``subrepos`` from the ``[codegraph]`` table of a seeded config.

    Federation links one checkout to other checkouts, which the seed does not
    carry. The source's children are its own: absolute paths to other repos'
    main checkouts, each on whatever branch it holds. A per-ticket worktree
    that inherited them would fan its queries out to code on unrelated
    branches. It starts unfederated instead; ``cgh federate add`` re-links it.

    The assignment is cut line by line rather than by re-emitting the parsed
    file: a re-emit drops comments and flattens nested tables such as
    ``[plugin.codegen]``. A multi-line array is followed to its closing
    bracket. Returns the removed entries, empty when there were none. If the
    edited text does not parse, the file is left untouched and nothing is
    reported as removed."""
    import tomllib

    try:
        text = config_path.read_text(encoding="utf-8")
        entries = list(tomllib.loads(text).get("codegraph", {}).get("subrepos", []))
    except (OSError, tomllib.TOMLDecodeError):
        return []
    if not entries:
        return []

    kept: list[str] = []
    table = ""
    depth = 0  # open brackets of a subrepos array still being skipped
    for line in text.splitlines(keepends=True):
        if depth:
            depth += line.count("[") - line.count("]")
            continue
        header = _TABLE_HEADER.match(line)
        if header:
            table = header.group(1)
        elif table == "codegraph" and _SUBREPOS_KEY.match(line):
            value = line.split("=", 1)[1]
            depth = value.count("[") - value.count("]")
            continue
        kept.append(line)

    edited = "".join(kept)
    try:
        if "subrepos" in tomllib.loads(edited).get("codegraph", {}):
            return []
    except tomllib.TOMLDecodeError:
        return []
    config_path.write_text(edited, encoding="utf-8")
    return [str(e) for e in entries]


def relocate_store(from_root: str | Path, to_root: str | Path) -> dict:
    """Seed ``to_root``'s .codegraph from ``from_root``'s.

    Copies the graph DB, the FTS DB, the knowledge/plan store and the config,
    then rewrites every stored path and embedded id from the source root to the
    target root. The target's ``.codegraph`` directory must already exist (run
    ``init_project`` first). Returns a summary dict; the caller is expected to
    run an incremental reindex afterward so branch-changed files are refreshed.

    Raises ``RelocateError`` if the source has no graph to copy.
    """
    from_root = Path(from_root).resolve()
    to_root = Path(to_root).resolve()
    from_cg = from_root / ".codegraph"
    to_cg = to_root / ".codegraph"
    to_cg.mkdir(parents=True, exist_ok=True)

    backend = _backend(from_root)
    graph_file = _DUCKDB_FILE if backend == "duckdb" else _SQLITE_FILE
    if not (from_cg / graph_file).exists():
        raise RelocateError(f"no {graph_file} under {from_cg} to seed from")

    # The calling process may already hold the target's graph open (init probes
    # the existing store first). DuckDB refuses a second open of the same file
    # with a different configuration, and the copy replaces the file under it,
    # so every cached connection to the target is released before anything moves.
    reset_connection(to_root)

    copied: list[str] = []
    for name in (graph_file, _FTS_FILE, _CALL_LOG_FILE, _CONFIG_FILE):
        src = from_cg / name
        if not src.exists():
            continue
        dst = to_cg / name
        if name == _DUCKDB_FILE:
            _copy_duckdb(src, dst)
        elif name == _CONFIG_FILE:
            shutil.copy2(src, dst)
        else:
            _copy_sqlite(src, dst)
        copied.append(name)

    old_prefix = str(from_root) + os.sep
    new_prefix = str(to_root) + os.sep
    rewritten = 0
    if backend == "duckdb":
        rewritten += _rewrite_duckdb(to_cg / graph_file, old_prefix, new_prefix)
    else:
        rewritten += _rewrite_sqlite_graph(to_cg / graph_file, old_prefix, new_prefix)
    if _FTS_FILE in copied:
        rewritten += _rewrite_fts(to_cg / _FTS_FILE, old_prefix, new_prefix)
    if _CALL_LOG_FILE in copied:
        rewritten += _rewrite_call_log_refs(
            to_cg / _CALL_LOG_FILE, old_prefix, new_prefix
        )

    _rewrite_scan_meta(from_root, to_root)
    dropped = _drop_subrepos(to_cg / _CONFIG_FILE) if _CONFIG_FILE in copied else []

    return {
        "backend": backend,
        "copied": copied,
        "rewritten_rows": rewritten,
        "dropped_subrepos": dropped,
        "from_root": str(from_root),
        "to_root": str(to_root),
    }
