# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-09-15
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: run_generation ties the pieces together: pick the reference,
#              clear it through the egress gate (unless the backend is local),
#              generate against it, and write the target. The safety rails the
#              council asked for live here: a cloud egress is refused on a
#              gated reference, the target is confined to the repo and never
#              clobbered without force, and the generated bytes are a proposal
#              to verify, never trusted because a later lint run is green.

from __future__ import annotations

from pathlib import Path

from .gate import egress_decision
from .generate import Backend, generate_code
from .picker import CodegenError, _confine, pick_reference


def run_generation(
    repo_root: str | Path,
    spec: str,
    target: str,
    reference: str | None = None,
    *,
    config: dict,
    backend: Backend,
    force: bool = False,
    to_stdout: bool = False,
    verify: str | None = None,
    max_attempts: int = 1,
    extend: bool = False,
) -> dict:
    """Generate the code for ``target`` and, unless ``to_stdout``, write it.

    With ``verify`` (a shell check, exit 0 = pass) and ``max_attempts`` > 1,
    it self-corrects: write, run the check, and on failure feed the check's
    output plus the previous attempt back to the model and regenerate, up to
    ``max_attempts``. That is how the loop catches what a first pass misses
    (a generated backend that forgot to commit fails the check, and the
    failure text drives the fix), turning "verify, don't trust" into a
    closed loop instead of a manual review.

    With ``extend``, the target must already exist and is added to rather than
    written over: the model receives the current file and returns only the
    block to append. That is the safe way to grow a file, since the existing
    content is never in the model's output and so cannot be dropped by a
    careless regeneration. The file is then its own style reference, and no
    sibling is picked unless one is named explicitly.

    Returns a result dict. Raises CodegenError for a bad target, a gated
    reference, or a refused overwrite.
    """
    root = Path(repo_root).resolve()

    tgt_probe = _confine(root, target)
    if tgt_probe is None:
        raise CodegenError(f"target {target!r} is outside the repo")

    existing_text: str | None = None
    if extend:
        if not tgt_probe.is_file():
            raise CodegenError(
                f"target {target} does not exist; generate it before extending it"
            )
        existing_text = tgt_probe.read_text(encoding="utf-8", errors="replace")

    if extend and reference is None:
        # The file being extended is its own best style example, and it is
        # already going to the model as the text to append to.
        pick = {
            "reference": None,
            "reason": "extending the target, which is its own reference",
            "graph_available": False,
        }
        ref_rel = None
        ref_path = tgt_probe
    else:
        pick = pick_reference(root, target, reference)
        ref_rel = pick["reference"]
        if ref_rel is None:
            raise CodegenError(pick["reason"])
        ref_path = _confine(root, ref_rel)
        if ref_path is None or not ref_path.is_file():
            raise CodegenError(f"reference {ref_rel!r} is not a readable file")

    # Egress gate: a cloud backend sees the reference's contents, so the
    # reference must clear the same checks as any other departure. A local
    # backend never leaves the machine, so it skips the gate, like the rest
    # of cgh.
    if backend.is_local:
        egress = "local backend (no egress)"
    else:
        departing = ref_rel or target
        allowed, reason = egress_decision(root, ref_path, config)
        if not allowed:
            _audit(root, "codegen_egress_denied", f"{departing}: {reason}")
            raise CodegenError(f"egress refused for reference {departing}: {reason}")
        egress = reason

    refs: list[tuple[str, str]] = []
    if ref_rel is not None:
        refs.append((ref_rel, ref_path.read_text(encoding="utf-8", errors="replace")))

    # Clobber check once, up front; the retry loop then overwrites its own
    # attempts freely (verify needs the file on disk to check it). Extending
    # never clobbers, so it is exempt.
    tgt = None
    if not to_stdout:
        tgt = tgt_probe
        if tgt.exists() and not force and not extend:
            raise CodegenError(
                f"target {target} already exists; pass force to overwrite"
            )

    do_verify = bool(verify) and not to_stdout
    prior: tuple[str, str] | None = None
    verified: bool | None = None
    written = False
    attempts = 0
    result = None
    while attempts < max(1, max_attempts):
        attempts += 1
        result = generate_code(
            spec,
            refs,
            backend,
            target=target,
            prior=prior,
            existing=existing_text,
        )
        if to_stdout or tgt is None:
            break
        if existing_text is not None:
            # Rebuild from the original every attempt, so a retry appends to
            # the file as it was rather than stacking onto its own last try.
            body = _append_into(existing_text, result.code)
        else:
            body = result.code if result.code.endswith("\n") else result.code + "\n"
        tgt.parent.mkdir(parents=True, exist_ok=True)
        tgt.write_text(body, encoding="utf-8")
        written = True
        if not do_verify:
            break
        ok, output = _run_verify(root, verify)  # type: ignore[arg-type]
        verified = ok
        if ok:
            break
        prior = (result.code, output)

    # Extending must never leave the file worse than it was found. A new file
    # that fails its check is a draft worth reading; an existing file that
    # fails one has been damaged, and the last attempt can be truncated or
    # unparsable. So put the original back and report the failure instead.
    rolled_back = False
    if extend and written and do_verify and not verified and existing_text is not None:
        tgt.write_text(existing_text, encoding="utf-8")  # type: ignore[union-attr]
        written = False
        rolled_back = True

    if result is None:  # unreachable: the loop always runs at least once
        raise CodegenError("generation produced no result")
    _audit(
        root,
        "codegen_extended" if extend else "codegen_generated",
        f"{target} <- {ref_rel or '(itself)'} ({backend.name}, "
        f"{attempts} attempt(s), verified={verified})",
    )

    return {
        "target": target,
        "reference": ref_rel,
        "reason": pick["reason"],
        "lines": len(result.code.splitlines()),
        "cost": result.cost,
        "backend": result.backend,
        "egress": egress,
        "written": written,
        "graph_available": pick["graph_available"],
        "attempts": attempts,
        "verified": verified,
        "extended": extend,
        "rolled_back": rolled_back,
        "code": result.code if to_stdout else "",
    }


def _append_into(existing: str, block: str) -> str:
    """Put ``block`` at the end of ``existing``, but before a trailing
    `if __name__ == "__main__":` guard.

    That guard is a runner, not content, and it is conventionally the last
    thing in the file. Appending after it works but reads as a mistake, and
    for a module that does real work under the guard it would leave the new
    code unreachable from a direct run.
    """
    lines = existing.rstrip("\n").split("\n")
    cut = len(lines)
    for i, line in enumerate(lines):
        if line.startswith('if __name__ == "__main__":') or line.startswith(
            "if __name__ == '__main__':"
        ):
            cut = i
            break

    head = "\n".join(lines[:cut]).rstrip("\n")
    tail = "\n".join(lines[cut:]).strip("\n")
    body = head + "\n\n" + block.strip("\n") + "\n"
    if tail:
        body += "\n" + tail + "\n"
    return body


def _run_verify(root: Path, command: str) -> tuple[bool, str]:
    """Run the verify command in ``root``; True on exit 0. The captured output
    (capped) is fed back to the model on failure. argv-only, timed, no shell."""
    import shlex
    import subprocess

    from codegraph.plugin_api import quiet_subprocess_kwargs

    argv = shlex.split(command)
    if not argv:
        return True, ""
    try:
        proc = subprocess.run(
            argv,
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
            **quiet_subprocess_kwargs(),
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        return False, f"the verify command could not run: {exc}"
    return proc.returncode == 0, (proc.stdout + proc.stderr)[-4000:]


def _audit(root: Path, event: str, detail: str) -> None:
    from codegraph.plugin_api import activity_log

    activity_log(root, event, detail)
