# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-09-15
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: run_generation ties the pieces together: pick the reference,
#              clear it through the egress gate (unless the backend is local),
#              generate against it, and write the target. The safety rails the
#              council asked for live here: a cloud egress is refused on a
#              gated reference, the target is confined to the repo and never
#              clobbered without force, and the generated bytes are a proposal
#              to verify, never trusted because a later lint run is green.

from __future__ import annotations

from pathlib import Path

from .gate import egress_decision
from .generate import Backend, generate_code
from .picker import CodeWriteError, _confine, pick_reference


def _select_reference(
    root: Path, pick: dict, backend: Backend, config: dict
) -> tuple[str, Path, str, str | None]:
    """Choose the reference to actually mirror, honoring the egress gate.

    For a cloud backend the top-ranked pick may carry a confidential or PII
    finding, which the gate refuses. Rather than fail the whole generation,
    walk the ranked candidates and take the first that clears the gate, so an
    auto-pick lands on a sendable reference instead of stopping on the first
    one that happens to hold a secret. A local backend never leaves the
    machine, so it skips the gate and keeps the top pick.

    Returns ``(ref_rel, ref_path, egress_reason, note)``. ``note`` is a human
    string when the choice fell back off the top pick (so the caller can say
    why the mirrored file is not the one first proposed), else None. Raises
    CodeWriteError when no candidate is usable.
    """
    ref_top = pick["reference"]
    if ref_top is None:
        raise CodeWriteError(pick["reason"])

    def _readable(rel: str) -> Path | None:
        p = _confine(root, rel)
        return p if (p is not None and p.is_file()) else None

    if backend.is_local:
        p = _readable(ref_top)
        if p is None:
            raise CodeWriteError(f"reference {ref_top!r} is not a readable file")
        return ref_top, p, "local backend (no egress)", None

    # Cloud backend: the reference's bytes leave the machine, so every
    # candidate must clear the gate. Try them in rank order; the top pick is
    # candidates[0], so an ungated top pick is chosen with no fallback note.
    ordered = pick["candidates"] or [ref_top]
    denials: list[str] = []
    for cand in ordered:
        p = _readable(cand)
        if p is None:
            denials.append(f"{cand}: not a readable file")
            continue
        allowed, reason = egress_decision(root, p, config)
        if allowed:
            note = None
            if cand != ref_top:
                note = (
                    f"top pick {ref_top} was refused by the egress gate; "
                    f"mirrored the next clear candidate {cand} instead"
                )
            return cand, p, reason, note
        denials.append(f"{cand}: {reason}")
        _audit(root, "codegen_egress_denied", f"{cand}: {reason}")

    if len(denials) == 1:
        raise CodeWriteError(f"egress refused for reference {denials[0]}")
    raise CodeWriteError(
        "every candidate reference was refused by the egress gate; "
        + "; ".join(denials)
    )


def run_generation(
    repo_root: str | Path,
    spec: str,
    target: str,
    reference: str | None = None,
    *,
    config: dict,
    backend: Backend,
    force: bool = False,
    to_stdout: bool = False,
    verify: str | None = None,
    max_attempts: int = 1,
) -> dict:
    """Generate the code for ``target`` and, unless ``to_stdout``, write it.

    With ``verify`` (a shell check, exit 0 = pass) and ``max_attempts`` > 1,
    it self-corrects: write, run the check, and on failure feed the check's
    output plus the previous attempt back to the model and regenerate, up to
    ``max_attempts``. That is how the loop catches what a first pass misses
    (a generated backend that forgot to commit fails the check, and the
    failure text drives the fix), turning "verify, don't trust" into a
    closed loop instead of a manual review.

    Returns a result dict. Raises CodeWriteError for a bad target, a gated
    reference, or a refused overwrite.
    """
    root = Path(repo_root).resolve()

    pick = pick_reference(root, target, reference)
    ref_rel, ref_path, egress, ref_note = _select_reference(root, pick, backend, config)
    ref_text = ref_path.read_text(encoding="utf-8", errors="replace")

    # Clobber check once, up front; the retry loop then overwrites its own
    # attempts freely (verify needs the file on disk to check it).
    tgt = None
    if not to_stdout:
        tgt = _confine(root, target)
        if tgt is None:
            raise CodeWriteError(f"target {target!r} is outside the repo")
        if tgt.exists() and not force:
            raise CodeWriteError(
                f"target {target} already exists; pass force to overwrite"
            )

    do_verify = bool(verify) and not to_stdout
    prior: tuple[str, str] | None = None
    verified: bool | None = None
    written = False
    attempts = 0
    result = None
    while attempts < max(1, max_attempts):
        attempts += 1
        result = generate_code(
            spec, [(ref_rel, ref_text)], backend, target=target, prior=prior
        )
        if to_stdout or tgt is None:
            break
        body = result.code if result.code.endswith("\n") else result.code + "\n"
        tgt.parent.mkdir(parents=True, exist_ok=True)
        tgt.write_text(body, encoding="utf-8")
        written = True
        if not do_verify:
            break
        ok, output = _run_verify(root, verify)  # type: ignore[arg-type]
        verified = ok
        if ok:
            break
        prior = (result.code, output)

    if result is None:  # unreachable: the loop always runs at least once
        raise CodeWriteError("generation produced no result")
    _audit(
        root,
        "codegen_generated",
        f"{target} <- {ref_rel} ({backend.name}, {attempts} attempt(s), "
        f"verified={verified})",
    )

    return {
        "target": target,
        "reference": ref_rel,
        "reason": ref_note or pick["reason"],
        "ref_fallback": ref_note,
        "lines": len(result.code.splitlines()),
        "cost": result.cost,
        "backend": result.backend,
        "egress": egress,
        "written": written,
        "graph_available": pick["graph_available"],
        "attempts": attempts,
        "verified": verified,
        "code": result.code if to_stdout else "",
    }


def _run_verify(root: Path, command: str) -> tuple[bool, str]:
    """Run the verify command in ``root``; True on exit 0. The captured output
    (capped) is fed back to the model on failure. argv-only, timed, no shell."""
    import shlex
    import subprocess

    from codegraph.plugin_api import quiet_subprocess_kwargs

    argv = shlex.split(command)
    if not argv:
        return True, ""
    try:
        proc = subprocess.run(
            argv,
            cwd=str(root),
            capture_output=True,
            text=True,
            timeout=180,
            check=False,
            **quiet_subprocess_kwargs(),
        )
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError) as exc:
        return False, f"the verify command could not run: {exc}"
    return proc.returncode == 0, (proc.stdout + proc.stderr)[-4000:]


def _audit(root: Path, event: str, detail: str) -> None:
    from codegraph.plugin_api import activity_log

    activity_log(root, event, detail)
