# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-04-12
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT & CC BY-NC-SA (https://www.altikva.com/licenses/LICENSE-1.0)"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: HTML generation: self-contained HTML files with Mermaid diagrams
#              and browser opening.

from __future__ import annotations

import html
import tempfile
from pathlib import Path

_HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>codegraph, {title}</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: #0d1117;
    color: #c9d1d9;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
  }}
  header {{
    background: #161b22;
    border-bottom: 1px solid #30363d;
    padding: 16px 24px;
    display: flex;
    align-items: center;
    gap: 16px;
  }}
  header h1 {{
    font-size: 18px;
    font-weight: 600;
    color: #58a6ff;
  }}
  header .meta {{
    font-size: 13px;
    color: #8b949e;
  }}
  header .scope {{
    background: #1f6feb33;
    color: #58a6ff;
    padding: 2px 10px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 500;
  }}
  .controls {{
    background: #161b22;
    border-bottom: 1px solid #30363d;
    padding: 8px 24px;
    display: flex;
    gap: 8px;
  }}
  .controls button {{
    background: #21262d;
    color: #c9d1d9;
    border: 1px solid #30363d;
    padding: 5px 12px;
    border-radius: 6px;
    cursor: pointer;
    font-size: 12px;
  }}
  .controls button:hover {{ background: #30363d; }}
  .controls button.active {{ background: #1f6feb; border-color: #1f6feb; color: #fff; }}
  main {{
    flex: 1;
    display: flex;
    justify-content: center;
    align-items: flex-start;
    padding: 24px;
    overflow: auto;
  }}
  .mermaid {{
    background: #0d1117;
    max-width: 100%;
  }}
  .mermaid svg {{ max-width: 100%; height: auto; }}
  footer {{
    background: #161b22;
    border-top: 1px solid #30363d;
    padding: 8px 24px;
    font-size: 11px;
    color: #484f58;
    text-align: center;
  }}
  footer a {{ color: #58a6ff; text-decoration: none; }}
</style>
</head>
<body>
<header>
  <h1>codegraph</h1>
  <span class="scope">{scope}</span>
  <span class="meta">{meta}</span>
</header>
<div class="controls">
  <button onclick="zoomIn()">Zoom +</button>
  <button onclick="zoomOut()">Zoom -</button>
  <button onclick="resetZoom()">Reset</button>
  <button onclick="downloadSVG()">Download SVG</button>
</div>
<main>
  <pre class="mermaid">
{mermaid}
  </pre>
</main>
<footer>
  Generated by <a href="https://github.com/altikva/codegraph">codegraph</a>, {timestamp}
</footer>
<script src="https://cdn.jsdelivr.net/npm/mermaid@11.4.1/dist/mermaid.min.js"
        integrity="sha384-rbtjAdnIQE/aQJGEgXrVUlMibdfTSa4PQju4HDhN3sR2PmaKFzhEafuePsl9H/9I"
        crossorigin="anonymous"></script>
<script>
  mermaid.initialize({{
    startOnLoad: true,
    theme: 'dark',
    themeVariables: {{
      primaryColor: '#1f6feb',
      primaryTextColor: '#c9d1d9',
      primaryBorderColor: '#30363d',
      lineColor: '#484f58',
      secondaryColor: '#161b22',
      tertiaryColor: '#21262d',
      fontSize: '14px',
    }},
    flowchart: {{ curve: 'basis', padding: 16 }},
    securityLevel: 'loose',
  }});

  let currentZoom = 1;
  function zoomIn() {{ currentZoom *= 1.2; applyZoom(); }}
  function zoomOut() {{ currentZoom /= 1.2; applyZoom(); }}
  function resetZoom() {{ currentZoom = 1; applyZoom(); }}
  function applyZoom() {{
    const svg = document.querySelector('.mermaid svg');
    if (svg) svg.style.transform = `scale(${{currentZoom}})`;
  }}
  function downloadSVG() {{
    const svg = document.querySelector('.mermaid svg');
    if (!svg) return;
    const blob = new Blob([svg.outerHTML], {{type: 'image/svg+xml'}});
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'codegraph-{scope}.svg';
    a.click();
  }}
</script>
</body>
</html>"""


def generate_html(
    mermaid_code: str,
    scope: str,
    root: str,
    meta: str = "",
) -> str:
    """Generate a self-contained HTML file with Mermaid diagram."""
    from datetime import datetime

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    repo_name = Path(root).name

    return _HTML_TEMPLATE.format(
        title=f"{repo_name}: {scope}",
        scope=scope,
        meta=meta or repo_name,
        mermaid=html.escape(mermaid_code),
        timestamp=timestamp,
    )


def open_in_browser(html_content: str, filename: str = "codegraph.html") -> Path:
    """Write HTML to a temp file and open in default browser."""
    import webbrowser

    tmp_dir = Path(tempfile.gettempdir()) / "codegraph"
    tmp_dir.mkdir(exist_ok=True)
    out_path = tmp_dir / filename
    out_path.write_text(html_content, encoding="utf-8")
    webbrowser.open(f"file://{out_path}")
    return out_path
