# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# __creation__ = 2026-09-15
# __author__ = "jndjama (Joy Ndjama)"
# __copyright__ = "Copyright 2026 ALTIKVA."
# __licence__ = "MIT"
# -#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#
# Description: run_generation ties the pieces together: pick the reference,
#              clear it through the egress gate (unless the backend is local),
#              generate against it, and write the target. The safety rails the
#              council asked for live here: a cloud egress is refused on a
#              gated reference, the target is confined to the repo and never
#              clobbered without force, and the generated bytes are a proposal
#              to verify, never trusted because a later lint run is green.

from __future__ import annotations

from pathlib import Path

from .gate import egress_decision
from .generate import Backend, generate_code
from .picker import CodeWriteError, _confine, pick_reference


def run_generation(
    repo_root: str | Path,
    spec: str,
    target: str,
    reference: str | None = None,
    *,
    config: dict,
    backend: Backend,
    force: bool = False,
    to_stdout: bool = False,
) -> dict:
    """Generate the code for ``target`` and, unless ``to_stdout``, write it.

    Returns a result dict. Raises CodeWriteError for a bad target, a gated
    reference, or a refused overwrite, so a caller never silently produces or
    clobbers a file. The generated code is returned/written as-is; callers
    verify it by running the checks, never by trusting it.
    """
    root = Path(repo_root).resolve()

    pick = pick_reference(root, target, reference)
    ref_rel = pick["reference"]
    if ref_rel is None:
        raise CodeWriteError(pick["reason"])
    ref_path = _confine(root, ref_rel)
    if ref_path is None or not ref_path.is_file():
        raise CodeWriteError(f"reference {ref_rel!r} is not a readable file")

    # Egress gate: a cloud backend sees the reference's contents, so the
    # reference must clear the same checks as any other departure. A local
    # backend never leaves the machine, so it skips the gate, like the rest
    # of cgh.
    if backend.is_local:
        egress = "local backend (no egress)"
    else:
        allowed, reason = egress_decision(root, ref_path, config)
        if not allowed:
            _audit(root, "codewrite_egress_denied", f"{ref_rel}: {reason}")
            raise CodeWriteError(f"egress refused for reference {ref_rel}: {reason}")
        egress = reason

    ref_text = ref_path.read_text(encoding="utf-8", errors="replace")
    result = generate_code(spec, [(ref_rel, ref_text)], backend)

    written = False
    if not to_stdout:
        tgt = _confine(root, target)
        if tgt is None:
            raise CodeWriteError(f"target {target!r} is outside the repo")
        if tgt.exists() and not force:
            raise CodeWriteError(
                f"target {target} already exists; pass force to overwrite"
            )
        tgt.parent.mkdir(parents=True, exist_ok=True)
        body = result.code if result.code.endswith("\n") else result.code + "\n"
        tgt.write_text(body, encoding="utf-8")
        written = True
        _audit(
            root,
            "codewrite_generated",
            f"{target} <- {ref_rel} ({backend.name}, {len(body.splitlines())} lines)",
        )

    return {
        "target": target,
        "reference": ref_rel,
        "reason": pick["reason"],
        "lines": len(result.code.splitlines()),
        "cost": result.cost,
        "backend": result.backend,
        "egress": egress,
        "written": written,
        "graph_available": pick["graph_available"],
        "code": result.code if to_stdout else "",
    }


def _audit(root: Path, event: str, detail: str) -> None:
    from codegraph.plugin_api import activity_log

    activity_log(root, event, detail)
